// FizzBuzz Question
// list out number 1-100, multiples of 3 print "fizz", multiples of 5 print "buzz"
// multiples of 3 and 5 "fizzbuz"

var array = [];
var fizzbuzz = function(){
    for(var i=1; i<101; i++){
        if(i%15===0){
            array.push("FizzBuzz");
        }else if (i%3===0){
            array.push("Fizz");
        }else if (i%5===0){
            array.push("Buzz");
        }else{
            array.push(i);
        }
    }
    console.log(array);
};

fizzbuzz();

// Fibonacci Sequence
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    var sequence = function(){
        var a = 0;
        var b = 1;
        var c;
        var sum = 0;
        for (var i = 2; i <= 100; i++){
            c = a + b;
            a = b;
            b = c;
            if(b % 2 === 0 && b < 4000000){
                sum = sum + b
            }
        }
        return sum; 
    }

sequence();